-- Crear la base de datos
CREATE DATABASE IF NOT EXISTS ecommerce;
USE ecommerce;

-- TABLA CLIENTE
CREATE TABLE IF NOT EXISTS cliente (
  id INT AUTO_INCREMENT PRIMARY KEY,
  nombre VARCHAR(100) NOT NULL,
  email VARCHAR(120) UNIQUE NOT NULL
);

-- TABLA PEDIDO (Relación CLIENTE 1 --- N PEDIDO)
CREATE TABLE IF NOT EXISTS pedido (
  id INT AUTO_INCREMENT PRIMARY KEY,
  cliente_id INT,
  fecha TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (cliente_id) REFERENCES cliente(id)
);

-- TABLA PRODUCTO
CREATE TABLE IF NOT EXISTS producto (
  id INT AUTO_INCREMENT PRIMARY KEY,
  nombre VARCHAR(150) NOT NULL,
  precio DECIMAL(10,2) NOT NULL
);

-- TABLA CATEGORIA
CREATE TABLE IF NOT EXISTS categoria (
  id INT AUTO_INCREMENT PRIMARY KEY,
  nombre VARCHAR(100) NOT NULL
);

-- TABLA INTERMEDIA CONTIENE (PEDIDO N --- N PRODUCTO)
CREATE TABLE IF NOT EXISTS pedido_producto (
  id INT AUTO_INCREMENT PRIMARY KEY,
  pedido_id INT NOT NULL,
  producto_id INT NOT NULL,
  cantidad INT NOT NULL,
  FOREIGN KEY (pedido_id) REFERENCES pedido(id),
  FOREIGN KEY (producto_id) REFERENCES producto(id)
);

-- TABLA INTERMEDIA PERTENECE_A (PRODUCTO N --- N CATEGORIA)
CREATE TABLE IF NOT EXISTS categoria_producto (
  id INT AUTO_INCREMENT PRIMARY KEY,
  producto_id INT NOT NULL,
  categoria_id INT NOT NULL,
  FOREIGN KEY (producto_id) REFERENCES producto(id),
  FOREIGN KEY (categoria_id) REFERENCES categoria(id)
);      